# Generated by Django 5.0 on 2023-12-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
