# Generated by Django 5.0 on 2023-12-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_artiles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Назва'),
        ),
    ]
