# Generated by Django 5.0 on 2023-12-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_artiles_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiles',
            name='anons',
        ),
    ]
