# Generated by Django 5.0 on 2023-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursetopic_product_why_this_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='course_topics',
        ),
        migrations.AddField(
            model_name='product',
            name='course_topics',
            field=models.TextField(default='wow'),
            preserve_default=False,
        ),
    ]
