# Generated by Django 5.0 on 2023-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_topics_product_topics1_product_topics2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='case1',
            field=models.TextField(default='wqwe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='case2',
            field=models.TextField(default='wqwe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='case3',
            field=models.TextField(default='wqwe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='case4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='case5',
            field=models.TextField(default='wqwe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses_images/'),
        ),
    ]
