# Generated by Django 5.0 on 2023-12-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_product_case1_product_case2_product_case3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
