# Generated by Django 5.0 on 2023-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_product_name1_product_name2_product_name3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
