# Generated by Django 5.0 on 2023-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_product_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courses_image',
            field=models.ImageField(blank=True, upload_to='courses_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
