# Generated by Django 5.0 on 2023-12-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_product_courses_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='case1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='case2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='case3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='case4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='case5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='why_this_course',
        ),
        migrations.RemoveField(
            model_name='product',
            name='youtube_link',
        ),
    ]
